#Compose for project setup and application booting
services:
  install:
    image: $ORO_IMAGE:$ORO_IMAGE_TAG
    command: console oro:install --no-interaction --timeout=3600 --user-name="$ORO_USER_NAME" --user-email="$ORO_USER_EMAIL" --user-firstname="$ORO_USER_FIRSTNAME" --user-lastname="$ORO_USER_LASTNAME" --user-password="$ORO_USER_PASSWORD" --sample-data="$ORO_SAMPLE_DATA" --organization-name="$ORO_ORGANIZATION_NAME" --language=$ORO_LANGUAGE --formatting-code=$ORO_FORMATTING_CODE --application-url="$ORO_APP_PROTOCOL://$ORO_APP_DOMAIN" $ORO_INSTALL_OPTIONS
    user: $ORO_USER_RUNTIME
    env_file: .env
    depends_on:
      <<: *default-depends_on
    volumes:
      - cache:/var/www/oro/var/cache
      - public:/var/www/oro/public
      - public_storage:/var/www/oro/public/media
      - private_storage:/var/www/oro/var/data

  restore: &restore
    image: ${ORO_IMAGE_INIT}${ORO_LANGUAGE_SUFFIX-}:$ORO_IMAGE_TAG
    command: restore
    user: $ORO_USER_RUNTIME
    env_file: .env
    depends_on:
      <<: *default-depends_on
    volumes:
      - cache:/var/www/oro/var/cache
      - public:/var/www/oro/public
      - public_storage:/var/www/oro/public/media
      - private_storage:/var/www/oro/var/data

  init:
    image: ${ORO_IMAGE}:$ORO_IMAGE_TAG
    command: init
    env_file: .env
    volumes:
      - etc_nginx:/etc/nginx
      - run_php_fpm:/run/php-fpm
      - public:/var/www/oro/public

volumes:
  cache: {}
  public_storage: {}
  private_storage: {}
  etc_nginx: {}
  run_php_fpm: {}
  public: {}